// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxMo7LuJIek-vs92unqu1RSo0qcSrnPg',
    appId: '1:450244345904:web:3f5a382efd8a066cad2df5',
    messagingSenderId: '450244345904',
    projectId: 'test-661b4',
    authDomain: 'test-661b4.firebaseapp.com',
    storageBucket: 'test-661b4.appspot.com',
    measurementId: 'G-7413QNY6SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzwYwih_Omu5jpzHvw9WpyoNq388tH6hY',
    appId: '1:450244345904:android:4ab947ac70f2ff1cad2df5',
    messagingSenderId: '450244345904',
    projectId: 'test-661b4',
    storageBucket: 'test-661b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANmjZdl01NcXuXMTb-bJinGLWwXcswfX0',
    appId: '1:450244345904:ios:cfe934bcefb970d5ad2df5',
    messagingSenderId: '450244345904',
    projectId: 'test-661b4',
    storageBucket: 'test-661b4.appspot.com',
    iosClientId: '450244345904-idlpgv4h32ive3r80mtbpkan7f23ies6.apps.googleusercontent.com',
    iosBundleId: 'com.example.datawizTest',
  );
}
